// src\constants\NavigationStrings.jsx
export default {
    // Root
    AUTH_STACK: 'AUTH_STACK',
    MAIN_STACK: 'MAIN_STACK',

    // Auth
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    SESSION_SCREEN: 'SESSION_SCREEN',

    // Main Tabs
    HOME_TAB: 'HOME_TAB',
    PROFILE_TAB: 'PROFILE_TAB',

    // Profile Stack
    PROFILE_SCREEN: 'PROFILE_SCREEN',
    PROFILE_SETTINGS_SCREEN: 'PROFILE_SETTINGS_SCREEN',
    PROFILE_ORDER_SCREEN: 'PROFILE_ORDER_SCREEN',
    PROFILE_COLLABORATION_LIST: 'PROFILE_COLLABORATION_LIST',
}